language: python
python:
  - "3.6"
branches:
  only:
    - master
    - /^release\/*$/
before_install:
  - pip install wheel twine
scripts:
  - python ./setup.py sdist bdist
  - python -m twine upload ./dist/*

